### ISSUE TITLE
Running the powershell module through an Azure AutomationAccount doesn't work

### ISSUE THREAD

**Issue by magnusjak** [AvePoint/elements-samples#2]
Using the Connect-Elements command through an Azure AutomationAccount gives me the following error-message:
`The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
        $Response = Invoke-WebRequest -Uri $RequestUri -Method 'POST' -Body $Body -ErrorAction Stop
at Get-IdentityServiceToken<Process>, C:\Modules\User\Elements.Client\Api\ElementsCommon.ps1: line 50
at Connect-Elements<Process>, C:\Modules\User\Elements.Client\Public\ElementsConnectApi.ps1: line 23
at <ScriptBlock>, <No file>: line 117`

Is it possible to have this reworked to use the '-UseBasicParsing' parameter of the native 'Invoke-WebRequest' command as suggested in the error-message?

Running this locally on my own computer works perfectly. However I need to be able to automate this through Azure

**Comment by murray-zhao-avepoint** [comment]
Hi @magnusjak,
Thanks for your feedback, we will publish a new version on 10/9/2023 to fix this issue of our Oct release. then you could import the latest version of this powershell module. If any questions, please feel free to let me know.
Regards,

**Comment by magnusjak** [comment]
Thanks for the quick reply, I will look forward to testing the new version :)

**Comment by magnusjak** [comment]
Hi @murray-zhao-avepoint,

I have just tested the new version through my Azure AutomationAccount and can verify that it works!
Thanks for the help 😃
